[workspace]

members = [
    "carmine-api",
    "carmine-api-airdrop",
    "carmine-api-cache",
    "carmine-api-core",
    "carmine-api-db",
    "carmine-api-fetcher",
    "carmine-api-starknet",
]

default-members = ["carmine-api", "carmine-api-fetcher"]
